config/routes.rb
Rails.application.routes.draw do
  
  resources :table_prices do
    member do 
      get :confirm
    end
  end

  resources :rates do
    collection {post :import}
  end

  match '/rates_import', :controller => 'rates', :action => 'rates_import', via: [:get, :post]
 
  root 'static_pages#home'

  get 'search' => 'search_tax#search'

  get 'search_tax/index'
  get 'search_tax/search'

  resources :districts do
    get :autocomplete_district_name, :on => :collection
  end

  devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout' }
  resources :users

end

app/controllers/search_tax_controller.rb
class SearchTaxController < ApplicationController
  before_filter :authenticate_user!
  autocomplete :district, :name, :full => true

  #respond_to :html, :js

  def index
    
  end

  def search
  	origin = District.find_by_name(params[:rate][:district_origin_id].upcase) if params[:rate][:district_origin_id].present? 
  	target = District.find_by_name(params[:rate][:district_target_id].upcase) if params[:rate][:district_target_id].present?  
    @rate = Rate.find_by_district_origin_id_and_district_target_id(origin.id, target.id)
  end
end

app/helpers/search_tax_helper.rb
module SearchTaxHelper
end

app/views/search_tax/_rate.html.erb
<tr>
	<td><%= rate.id %></td>
	<td><%= rate.origin.name %></td>
	<td><%= rate.target.name %></td>
	<td class='quantity'><%= @rate.price.to_f %></td>
	<% if current_user.admin? %>
    <td><%= link_to "Editar", edit_rate_path(rate), class: 'btn btn-primary btn-sm' %></td>
    <td><%= link_to "Log", rate_path(rate), class: 'btn btn-default btn-sm' %></td>
  <% end %>
</tr>

app/views/search_tax/index.html.erb
<%= form_tag({:controller => "search_tax", :action => "search"}, :method => "get", :remote => true) do |f| %>

  <div class="center form-group">
    <%= autocomplete_field_tag 'rate[district_origin_id]', '', autocomplete_district_name_districts_path, :size => 30, style: "text-transform:uppercase", placeholder: "Informe a origem"  %>
    <%= autocomplete_field_tag 'rate[district_target_id]', '', autocomplete_district_name_districts_path, :size => 30, style: "text-transform:uppercase", placeholder: "Informe o destino" %>    
    <%= submit_tag("[+] Consulta", id: "soma_registro", class: "btn btn-success btn-sm") %> 
    <%= link_to 'Limpar', {:controller => 'search_tax', :action => 'index'}, class: 'btn btn-primary btn-sm' %>    
  </div>

<% end %>



<div id="messages"></div>
<br />  

    <div class="table-responsive">
      <table id="list_table_price" class="table table-striped">
        <thead>
          <tr>
            <th>No</th>
            <th>Origem</th>
            <th>Destino</th>
            <th>Valor</th>
            <th colspan="2"></th>
          </tr>
        </thead>

        <tbody>
          

        </tbody>
      </table>
    </div>    

<div id="result_soma"></div>

<div id="download_rates">
  <%= link_to "Download Excel", rates_path(@rates, format: :csv), class: "" %>
</div>

                        
<script type="text/javascript">
  
Number.prototype.formatMoney = function(c, d, t){
var n = this, 
    c = isNaN(c = Math.abs(c)) ? 2 : c, 
    d = d == undefined ? "." : d, 
    t = t == undefined ? "," : t, 
    s = n < 0 ? "-" : "", 
    i = parseInt(n = Math.abs(+n || 0).toFixed(c)) + "", 
    j = (j = i.length) > 3 ? j % 3 : 0;
   return s + (j ? i.substr(0, j) + t : "") + i.substr(j).replace(/(\d{3})(?=\d)/g, "$1" + t) + (c ? d + Math.abs(n - i).toFixed(c).slice(2) : "");
 };


function sumPrice() {
  var elements = document.getElementsByClassName('quantity');
  var sum = 0;

  for (i=0;i< elements.length;i++) {
    sum = sum + parseFloat(elements[i].innerHTML);
    };
  
  $('#result_soma').html("<div class='alert alert-success-center'><strong>Total: "+sum.formatMoney(2, ',', '.')+"</strong></div>");
  

}
</script>

app/views/search_tax/search.js.erb
<% if @rate.nil? -%>
  $("#messages").hide(300);
  $("#messages").empty();
  $("#messages").append("<div class='alert alert-danger'>Origem e destino não encontrado.</div>");
  $("#messages").show(300);
<% else -%>
  //$("#sumary").remove();
  $("#messages").hide(300);
  $("#messages").empty();
  $("#message").append("<div class='alert alert-success'>Origem e destino adicionado com sucesso.</div>");
  $(":input:not(input[type=submit])").val("");
  $("#messages").show(300);
  $("#list_table_price").append("<%= j( render "rate", rate: @rate ) %>")
  
  $("#result_soma").append("");
  sumPrice();
<% end -%>