config/routes.rb
Rails.application.routes.draw do
  
  resources :table_prices do
    member do 
      get :confirm
    end
  end

  resources :rates do
    collection {post :import}
  end

  match '/rates_import', :controller => 'rates', :action => 'rates_import', via: [:get, :post]
 
  root 'static_pages#home'

  get 'search' => 'search_tax#search'

  get 'search_tax/index'
  get 'search_tax/search'

  resources :districts do
    get :autocomplete_district_name, :on => :collection
  end

  devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout' }
  resources :users

end

app/models/rate.rb
class Rate < ActiveRecord::Base
	belongs_to :origin, class_name: 'District', foreign_key: 'district_origin_id'
	belongs_to :target, class_name: 'District', foreign_key: 'district_target_id'

	validates :district_origin_id, presence: true
	validates :district_target_id, presence: true
  validates :price, presence: true
  
	validates_uniqueness_of :district_origin_id, :scope => [:district_target_id], if: :diff_origin_and_target?

  scope :origin_and_target, -> { joins(:origin, :target).order('districts.name asc') }
	
  before_save :set_values_price
  after_save :modifi_price_invert_rate


  audited
  
  def diff_origin_and_target?
    district_origin_id !=  district_target_id
  end

  def modifi_price_invert_rate
    #procura pela rota invertida

    rate_invert = Rate.find_by_district_origin_id_and_district_target_id(self.district_target_id, self.district_origin_id)
    #cadastra ou atualiza o preco da rota invertida a rota
    if rate_invert.nil?
    	Rate.create!(district_origin_id: self.district_target_id, district_target_id: self.district_origin_id, price: price) 
    else
      Rate.where(id: rate_invert.id).update_all(price: self.price)    	
      #verifica usuario para log do sistema
      #user = find_current_user
      #if user.nil?
      user = User.find_by_email('servoscidade@servostaxi.com.br') 
      #end
      #puts ">>>>>>>>>>. user: #{user.id}"
      # cadastra log
      rate_invert.audits.create!(auditable_type: "Rate", user_id: user.id, user_type: "User", action: "update", audited_changes: @price_modify, version: count_version_audited(rate_invert) )
    end
  end

  def set_values_price
     #+ JSON.parse(self.changes['price'].to_json)]
     @price_modify = {"price" => self.changes['price']}
     #puts ">>>>>>>>>>>>>> parse: #{parse.class}"
     #parse = JSON.parse(@price_modify)
  end

  def self.to_csv
    CSV.generate do |csv|
      csv << ["Origem", "Destino", "Valor"]
      all.each do |rate|
        row = [rate.origin.name, rate.target.name, rate.price.to_f]
        csv << row
      end
    end
  end 

  def self.import(origin_id, file)
    CSV.foreach(file.path, headers: true) do |row|
      puts ">>>>>>>>>>>>>>>>. #{row[0]}"
      target = District.where(name: row[0]).first_or_create 
      price = row[1]
      rate = Rate.find_by_district_origin_id_and_district_target_id(origin_id, target.id)
      if rate.nil?
        Rate.create!(district_origin_id: origin_id, district_target_id: target.id, price: price) 
      else
       rate.update_attributes!(price: price)
      end 
    end
  end

  # def self.import(file)
  #   CSV.foreach(file.path, headers: true) do |row|
  #     target = District.where(name: row[0]).first_or_create 
  #     rate = Rate.find_by_district_origin_id_and_district_target_id(origem, target.id)
  #     if rate.nil?
  #       Rate.create!(district_origin_id: origin, district_target_id: target.id, price: price) 
  #     else
  #      rate.update_attributes!(price: price)
  #     end 
  #   end
  # end

  # def find_current_user
  # (1..Kernel.caller.length).each do |n|
  #   RubyVM::DebugInspector.open do |i|
  #     current_user = eval "current_user rescue nil", i.frame_binding(n)
  #     return current_user unless current_user.nil?
  #   end
  # end
  # return nil
  # end

  private
    def count_version_audited(rate)
      rate.audits.count
    end


end

app/controllers/rates_controller.rb
require 'iconv'
class RatesController < ApplicationController
  BOM = "\377\376" #Byte Order Mark
  before_filter :authenticate_user!
  before_action :set_rate, only: [:show, :edit, :update, :destroy]

  def rate_import
  end

  def import
    Rate.import(params[:origin_id], params[:file])
    redirect_to search_tax_index_path, flash: { success: 'Tabela importada com sucesso.' }
  end

  # GET /rates
  # GET /rates.json
  def index
    #@rates = Rate.paginate(page: params[:page])
    #@rates = Rate.joins(:origin, :target).order('districts.name asc')
    #@rates = Rate.all
    @rates = Rate.joins(:origin, :target).order('districts.name asc, targets_rates.name asc')
    filename = "tabela_de_preco.xls"
    respond_to do |format|
      format.html
      #format.xls { headers["Content-Disposition"] = "attachment; filename=\"#{filename}\"" }
      format.csv { export_csv(@rates) }
      #format.csv { render text: @rates.to_csv }
    end
  end

  # GET /rates/1
  # GET /rates/1.json
  def show
  end

  # GET /rates/new
  def new
    @rate = Rate.new
  end

  # GET /rates/1/edit
  def edit
  end

  # POST /rates
  # POST /rates.json
  def create
    @rate = Rate.new(rate_params)
    origin = District.find_by_name(params[:rate][:district_origin_id].upcase) if params[:rate][:district_origin_id].present? 
    target = District.find_by_name(params[:rate][:district_target_id].upcase) if params[:rate][:district_target_id].present?  
    @rate.district_origin_id = origin.id
    @rate.district_target_id = target.id
    respond_to do |format|
      if @rate.save
        format.html { redirect_to @rate, flash: { success: 'Rate was successfully created.' } }
        format.json { render :show, status: :created, location: @rate }
      else
        format.html { redirect_to rates_new_path }
        format.json { render json: @rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rates/1
  # PATCH/PUT /rates/1.json
  def update
    respond_to do |format|
      if @rate.update(rate_params)
        format.html { redirect_to @rate, flash: { success: 'Rate was successfully updated.' } }
        format.json { render :show, status: :ok, location: @rate }
      else
        format.html { render :edit }
        format.json { render json: @rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rates/1
  # DELETE /rates/1.json
  def destroy
    @rate.destroy
    respond_to do |format|
      format.html { redirect_to rates_url, notice: 'Rate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rate
      @rate = Rate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rate_params
      params.require(:rate).permit(:district_origin_id, :district_target_id, :price)
    end

    def export_csv(rates)
      #filename = I18n.l(Time.now, :format => :short) + "- TabelePreco.csv"
      filename = "TabelePreco.csv"
      content = rates.to_csv
      #content = BOM + Iconv.conv("utf-16le", "utf-8", content)
      send_data content, :filename => filename
    end

end

app/helpers/rates_helper.rb
module RatesHelper
	def parse_audit_rate(action, changed)
     if action == 'create'
        log = "criado com o valor: #{changed['price']}" 
     elsif action =='update' 
     	 log = "Alterado de #{changed['price'][0]} para #{changed['price'][1]}" 
     end
    log
	end

	def parse_audit_email(user)
		user.present? ? user.email : 'alterado pelo sistema' 
	end
end


#{"district_origin_id"=>329, "district_target_id"=>176, "price"=>25}

app/views/rates/_form.html.erb
<%= form_for(@rate) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <div class="form-group">
    <%#= f.label :district_origin_id, "Origem" %><br>
    <%#= f.select(:district_origin_id, District.order(:name).collect {|g| [g.name, g.id]}, {include_blank: "Informe a Origem"}, {class: "form-control"} ) %>
  </div>
  
  <div class="form-group">
    <%#= f.label :district_target_id, "Destino" %><br>
    <%#= f.select(:district_target_id, District.order(:name).collect {|g| [g.name, g.id]}, {include_blank: "Informe o Destino"}, {class: "form-control"} ) %>
  </div>
  
  <div class="form-group">
    <%#= f.label :price, "Valor" %><br>
    <%#= f.text_field :price, {class: "form-control"} %>
  </div>

  <div class="center form-group">
    <% if @rate.new_record? %>
      <%= f.autocomplete_field :district_origin_id, autocomplete_district_name_districts_path, :size => 30, style: "text-transform:uppercase", placeholder: "Informe a origem"  %>
      <%= f.autocomplete_field :district_target_id, autocomplete_district_name_districts_path, :size => 30, style: "text-transform:uppercase", placeholder: "Informe o destino"  %>
      <%= f.number_field :price, size: 10, placeholder: "0.00" %>
    <% else %>
      <%= text_field_tag :district_origin_id, @rate.origin.name, disabled: true %>
      <%= text_field_tag :district_origin_id, @rate.target.name, disabled: true %>
      <%= f.number_field :price, size: 10, placeholder: "0.00" %>
    <% end %>    

    <%= f.submit "Salvar", class: "btn btn-primary" %>    

  </div>

  
  <div class="form-group center">
    <%= link_to 'Listar Todos', search_tax_index_path, class: "btn btn-default" %>
    <%= link_to 'Exibir Log', @rate, class: "btn btn-default" %>
  </div>
<% end %>

app/views/rates/edit.html.erb
<h1>Editing Rate</h1>

<%= render 'form' %>

app/views/rates/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Listagem de Tarifas por Bairro</div>
  <div class="panel-body">
    <%= link_to 'Nova Tarifa', new_rate_path, class: "btn btn-primary btn-lg btn-block" %>
    <div class="table-responsive">
      <table id="list_table_price" class="table table-striped">
        <thead>
          <tr>
            <th>ID</th>
            <th>Origem</th>
            <th>Destino</th>
            <th>Valor</th>
            <th colspan="3">Options</th>
          </tr>
        </thead>

        <tbody>
          <% @rates.each do |rate| %>
            <tr>
              <td><%= rate.id %></td>
              <td><%= link_to rate.origin.name, rate.origin if rate.origin.present? %></td>
              <td><%= link_to rate.target.name, rate.target if rate.target.present? %></td>
              <td><%= rate.price.to_f %></td>
              <td><%= link_to 'Show', rate, class: "btn btn-info btn-sm" %></td>
              <td><%= link_to 'Edit', edit_rate_path(rate), class: "btn btn-primary btn-sm" %></td>
              <td><%= link_to 'Destroy', rate, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>    

 <div class="pagination">
    <%= will_paginate %>
  </div> 
  </div>
</div>

app/views/rates/index.xls.erb
<?xml version="1.0"?>
<?mso-application progid="Excel.Sheet"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">

  <ExcelWorkbook xmlns="urn:schemas-microsoft-com:office:excel">
    <WindowHeight>6795</WindowHeight>
    <WindowWidth>8460</WindowWidth>
    <WindowTopX>120</WindowTopX>
    <WindowTopY>15</WindowTopY>
    <ProtectStructure>False</ProtectStructure>
    <ProtectWindows>False</ProtectWindows>
  </ExcelWorkbook>

  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Origem</Data></Cell>
        <Cell><Data ss:Type="String">Destino</Data></Cell>
        <Cell><Data ss:Type="String">Valor</Data></Cell>
      </Row>
    <% @rates.each do |rate| %>
      <Row>
        <Cell><Data ss:Type="String"><%= rate.origin.name if rate.origin.present? %></Data></Cell>
        <Cell><Data ss:Type="String"><%= rate.target.name if rate.target.present? %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= rate.price.to_f %></Data></Cell>
      </Row>
    <% end %>
      <Row>
      </Row>
    </Table>
  </Worksheet>
</Workbook>

app/views/rates/new.html.erb
<h1>New Rate</h1>

<%= render 'form' %>

app/views/rates/rates_import.html.erb
<h2>Importar Tabela de Preços</h2>

<%= form_tag import_rates_path, multipart: true do %>
  <div class="form-group">
    <%= label_tag :origin_id, "Origem"  %> <br>
    <%= select_tag 'origin_id', options_from_collection_for_select(District.order(:name), 'id', 'name'), :prompt => "Selecione o bairro de origem", class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= file_field_tag :file %>
  </div>
  
  <div class="form-group">
    <%= submit_tag "Import" %>
  </div>
<% end %>

app/views/rates/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h2 class="panel-title">Tarifa do Bairro</h2>
  </div>

  <div class="panel-body">
		<p>
		  <strong>Origem:</strong>
		  <%= @rate.origin.name %>
		</p>

		<p>
		  <strong>Destino:</strong>
		  <%= @rate.target.name %>
		</p>

		<p>
		  <strong>Valor:</strong>
		  <%= @rate.price %>
		</p>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">Log de Modificações</div>
  <div class="panel-body">
    <div class="table-responsive">
      <table id="list_table_price" class="table table-striped">
        <thead>
          <tr>
            <th>Usuario</th>
            <th>Acao</th>
            <th>Data</th>
            <th>Modificação</th>
          </tr>
        </thead>

        <tbody>
          <% @rate.audits.where(auditable_type: 'Rate').each do |audit| %>
            <tr>
              <td><%= parse_audit_email(audit.user) %></td>
              <td><%= audit.action %></td>
              <td>
              <%= I18n.l(audit.created_at, format: '%d/%m/%Y')%> as <%= I18n.l(audit.created_at, format: '%H:%M') %>
              <%#=  Time.zone.parse(I18n.l(audit.created_at, format: '%d/%m/%Y %H:%M:%S'))  %>
              <%#= Time.strptime('2016-08-25 16:10:37', '%d/%m/%Y %H:%M:%S').in_time_zone(Time.zone) %>
              </td>
              <td><%= parse_audit_rate(audit.action, audit.audited_changes)%></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>    

  </div>
</div>

<div class="form-group">
  <%= link_to 'Editar',  edit_rate_path(@rate) , class: "btn btn-primary" %>
  <%= link_to 'Listar Todos', search_tax_index_path, class: "btn btn-default" %>
</div>